# 선형회귀 구현
---

In [1]:
# !pip install torch
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as opt

In [2]:
# torch random seed
torch.manual_seed(0)

In [3]:
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [4]:
print(X_train)
print(X_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [6]:
w = torch.zeros(1, requires_grad=True) # 가중치 초기화
print(w)

tensor([0.], requires_grad=True)


In [7]:
b = torch.zeros(1, requires_grad=True) # 편향 초기화
print(b)

tensor([0.], requires_grad=True)


In [8]:
# H(x) = wx + b
h = X_train * w + b
print(h)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [9]:
# cost function
cost = torch.mean((h - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [10]:
# SGD
optimizer = opt.SGD([w,b], lr=0.01)

In [11]:
# 기울기 0 초기화
optimizer.zero_grad()
# 비용함수 미분하여 gradient 계산 (.backward : w, b의 기울기 계산)
cost.backward()
# w, b 업데이트 (.step : 경사하강법 최적화)
optimizer.step()

In [12]:
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

w = torch.zeros(1, requires_grad=True) # 가중치 초기화
b = torch.zeros(1, requires_grad=True) # 편향 초기화

optimizer = opt.SGD([w,b], lr=0.01)
num_epochs = 1000

for epoch in range(num_epochs + 1) :
    h = X_train * w + b
    cost = torch.mean((h - y_train) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, num_epochs, w.item(), b.item(), cost.item()))

Epoch    0/1000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1000 W: 1.971, b: 0.066 Cost: 0.000633


## nn.Module로 구현

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as opt
torch.manual_seed(0)

In [14]:
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [15]:
model = nn.Linear(1, 1)

In [16]:
print(list(model.parameters())) # w와 b 저장

[Parameter containing:
tensor([[-0.0075]], requires_grad=True), Parameter containing:
tensor([0.5364], requires_grad=True)]


In [17]:
optimizer = opt.SGD(model.parameters(), lr=0.01)
num_epochs = 1000

for epoch in range(num_epochs + 1) :
    pred = model(X_train)
    cost = F.mse_loss(pred, y_train) # 평균제곱오차
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, num_epochs, cost.item()))

Epoch    0/1000 Cost: 14.786839
Epoch  100/1000 Cost: 0.125403
Epoch  200/1000 Cost: 0.077491
Epoch  300/1000 Cost: 0.047885
Epoch  400/1000 Cost: 0.029590
Epoch  500/1000 Cost: 0.018285
Epoch  600/1000 Cost: 0.011299
Epoch  700/1000 Cost: 0.006982
Epoch  800/1000 Cost: 0.004314
Epoch  900/1000 Cost: 0.002666
Epoch 1000/1000 Cost: 0.001647


In [18]:
new_val = torch.FloatTensor([[4.0]])

new_pred = model(new_val)

print(f'new_val <<{new_val}>> 에 대한 예측값 : <<{new_pred}>>')
print(list(model.parameters()))

new_val <<tensor([[4.]])>> 에 대한 예측값 : <<tensor([[7.9188]], grad_fn=<AddmmBackward0>)>>
[Parameter containing:
tensor([[1.9530]], requires_grad=True), Parameter containing:
tensor([0.1069], requires_grad=True)]


# 다중선형회귀 구현
---

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as opt
torch.manual_seed(0)

In [20]:
X1_train = torch.FloatTensor([[73],[93],[89],[96],[73]])
X2_train = torch.FloatTensor([[80],[88],[91],[98],[66]])
X3_train = torch.FloatTensor([[75],[93],[90],[100],[70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# w, b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [21]:
optimizer = opt.SGD([w1, w2, w3, b], lr=1e-5)
num_epochs = 1000
for epoch in range(num_epochs + 1) :
    h = X1_train * w1 + X2_train * w2 + X3_train * w3 + b
    cost = torch.mean((h-y_train)**2)
    # update
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100
    if epoch%100 == 0 :
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, num_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()))
    

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079378


In [22]:
X_train = torch.FloatTensor([
    [73, 80, 75],
    [93, 88, 93],
    [89, 91, 80],
    [96, 98, 100],
    [73, 66, 70]
])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [23]:
print(X_train.shape, y_train.shape)

torch.Size([5, 3]) torch.Size([5, 1])


In [24]:
# w, b, h
w = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
h = X_train.matmul(w) + b

In [25]:
optimizer = opt.SGD([w,b], lr=1e-5)
num_epochs = 1000

for epoch in range(num_epochs + 1) :
    h = X_train.matmul(w) + b
    cost = torch.mean((h - y_train) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print('Epoch {:4d}/{} hypothesis :{} Cost: {:.6f}'.format(
            epoch, num_epochs, h.squeeze().detach(), cost.item()))

Epoch    0/1000 hypothesis :tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/1000 hypothesis :tensor([154.0433, 185.0925, 175.8312, 198.5701, 141.2221]) Cost: 5.754573
Epoch  200/1000 hypothesis :tensor([154.0278, 185.0649, 175.9335, 198.5128, 141.2284]) Cost: 5.512386
Epoch  300/1000 hypothesis :tensor([154.0120, 185.0385, 176.0329, 198.4569, 141.2353]) Cost: 5.281667
Epoch  400/1000 hypothesis :tensor([153.9960, 185.0133, 176.1295, 198.4022, 141.2426]) Cost: 5.061907
Epoch  500/1000 hypothesis :tensor([153.9797, 184.9892, 176.2233, 198.3488, 141.2504]) Cost: 4.852424
Epoch  600/1000 hypothesis :tensor([153.9632, 184.9662, 176.3143, 198.2966, 141.2586]) Cost: 4.652731
Epoch  700/1000 hypothesis :tensor([153.9465, 184.9442, 176.4029, 198.2456, 141.2672]) Cost: 4.462265
Epoch  800/1000 hypothesis :tensor([153.9296, 184.9232, 176.4888, 198.1958, 141.2762]) Cost: 4.280604
Epoch  900/1000 hypothesis :tensor([153.9126, 184.9032, 176.5724, 198.1471, 141.2855]) Cost: 4.107261
Epoch 

## nn.Module로 구현

In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as opt
torch.manual_seed(0)

In [27]:
X_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [28]:
model = nn.Linear(3,1)

In [29]:
print(list(model.parameters())) # 3개의 w와 b

[Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752]], requires_grad=True), Parameter containing:
tensor([-0.4249], requires_grad=True)]


In [30]:
optimizer = opt.SGD(model.parameters(), lr=1e-5)

In [31]:
num_epochs = 2000
for epoch in range(num_epochs + 1) :
    pred = model(X_train)
    cost = F.mse_loss(pred, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100 == 0 :
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, num_epochs, cost.item()))

Epoch    0/2000 Cost: 35211.054688
Epoch  100/2000 Cost: 5.245598
Epoch  200/2000 Cost: 4.978477
Epoch  300/2000 Cost: 4.725472
Epoch  400/2000 Cost: 4.485765
Epoch  500/2000 Cost: 4.258754
Epoch  600/2000 Cost: 4.043709
Epoch  700/2000 Cost: 3.839999
Epoch  800/2000 Cost: 3.647048
Epoch  900/2000 Cost: 3.464262
Epoch 1000/2000 Cost: 3.291126
Epoch 1100/2000 Cost: 3.127121
Epoch 1200/2000 Cost: 2.971779
Epoch 1300/2000 Cost: 2.824605
Epoch 1400/2000 Cost: 2.685211
Epoch 1500/2000 Cost: 2.553164
Epoch 1600/2000 Cost: 2.428088
Epoch 1700/2000 Cost: 2.309596
Epoch 1800/2000 Cost: 2.197381
Epoch 1900/2000 Cost: 2.091092
Epoch 2000/2000 Cost: 1.990380


In [32]:
new_var = torch.FloatTensor([[73, 80, 75]])
new_pred = model(new_var)
print(new_pred)
print(list(model.parameters()))

tensor([[153.4909]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.8837, 0.8327, 0.3037]], requires_grad=True), Parameter containing:
tensor([-0.4149], requires_grad=True)]


# 클래스로 구현 
---

## 단순선형회귀

In [33]:
model = nn.Linear(1,1)
class LinearRegressionModel(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(1, 1)
        
    def forward(self, x) :
        return self.linear(x)
    
model=  LinearRegressionModel()

In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(0)

In [35]:
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [36]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [37]:
epochs = 200

for epoch in range(epochs + 1) :
    pred = model(X_train)
    cost = F.mse_loss(pred, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100 == 0 :
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epochs, cost.item()
      ))

Epoch    0/200 Cost: 13.261064
Epoch  100/200 Cost: 0.175937
Epoch  200/200 Cost: 0.108719


## 다중선형회귀

In [38]:
model= nn.Linear(3, 1)
class MultivariateLinearRegressionModel(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(3, 1)
        
    def forward(self, x) :
        return self.linear(x)

model = MultivariateLinearRegressionModel()

In [39]:
X_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [40]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [41]:
epochs = 200

for epoch in range(epochs + 1) :
    pred = model(X_train)
    cost = F.mse_loss(pred, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100 == 0 :
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epochs, cost.item()
      ))

Epoch    0/200 Cost: 31878.519531
Epoch  100/200 Cost: 4.456649
Epoch  200/200 Cost: 4.238406
